stages:
  - test
  - publish

test:
  stage: test
  image: ruby:3.3
  script:
    - bundle install
    - bundle exec rake test

publish:
  stage: publish
  image: ruby:3.3
  only:
    - tags
  script:
    - gem build foghorn.gemspec
    - |
      curl --fail --request POST \
        --header "Job-Token: ${CI_JOB_TOKEN}" \
        --form "file=@$(ls foghorn-*.gem)" \
        "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/rubygems/api/v1/gems"
