stages:
  - test
  - publish

test:
  stage: test
  image: ruby:3.3
  script:
    - bundle install
    - bundle exec rake test

publish:
  stage: publish
  image: ruby:3.3
  only:
    - tags
  script:
    - mkdir -p ~/.gem
    - |
      echo "---
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/rubygems: 'Bearer ${CI_JOB_TOKEN}'" > ~/.gem/credentials
    - chmod 0600 ~/.gem/credentials
    - gem build foghorn.gemspec
    - gem push foghorn-*.gem --host ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/rubygems
